apiVersion: v1
kind: Service
metadata:
  name: node-js-app
  labels:
    app: node-js-app
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: node-js-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-js-app
  name: node-js-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-js-app
  strategy: {}
  template:
    metadata:
      labels:
        app: node-js-app
      name: node-js-app
    spec:
      containers:
      - image: lucaiovio/node-web-app:1.0.9
        name: node-web-app
        resources: {}
        ports:
        - containerPort: 8080
status: {}